---
  - name: ensure presence of Homebrew Cask
    homebrew_tap: name="caskroom/cask" state=present

  - name: ensure required desktop applications
    homebrew_cask: name={{ item }} state=present
    with_items:
      - atom
      - box-sync
      - calibre
      - colloquy
      - firefox
      - google-chrome
      - libreoffice
      - rowanj-gitx
      - sequel-pro
      - skype
      - slack
      - spotify
      - vagrant
      - vienna
