---
- name: ubuntu-base
  sudo: True
  hosts: os_ubuntu
  tasks:
    - name: refresh Apt index
      apt: update-cache=yes
    - name: ensure Git
      apt: name=git state=present
    - name: ensure Curl
      apt: name=curl state=present
