---
  - name: ensure user account for Ansible
    user: name={{ ansible_ssh_user }} comment="Administrative account" uid={{ ansible_user_uid }} shell=/bin/bash password={{ ansible_user_password_sha512 }} state=present
    no_log: True
  - name: ensure SSH key for Ansible user account
    authorized_key: user={{ ansible_ssh_user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}" state=present
  - name: enable sudo for Ansible user account
    template: src=ansible_sudoer.j2 dest=/etc/sudoers.d/{{ ansible_ssh_user }} owner=root group=root mode=0600 validate='visudo -cf %s'
