---
  - name: ensure RDS MySQL instance
    rds:
      command: create
      instance_name: "{{ app_name }}-db"
      db_engine: MySQL
      engine_version: "5.6.27"
      size: 10
      instance_type: db.t2.micro
      maint_window: "Sun:22:15-Sun:23:15"
      backup_retention: 30
      backup_window: "21:05-22:05"
      aws_region: "{{ aws_region }}"
      multi_zone: yes
      publicly_accessible: yes
      subnet: "nets-{{ app_name }}-db"
      vpc_security_groups: "{{ security_group_db.group_id }}"
      username: "dbadmin"
      password: "{{ dba_password }}"
      tags:
        Application: "{{ app_name }}"
